global:
  enabled: true
  tlsDisable: false
# Vault Helm Chart Value Overrides
injector:
  enabled: false
  metrics:
    enabled: true

server:
  # Use the Enterprise Image
  image:
    repository: "hashicorp/vault-enterprise"
    tag: "1.8.4_ent"

  enterpriseLicense:
    # The name of the Kubernetes secret that holds the enterprise license. The
    # secret must be in the same namespace that Vault is installed into.
    secretName: "vault-license"
    # The key within the Kubernetes secret that holds the enterprise license.
    secretKey: "license"

  annotations:
    consul.hashicorp.com/connect-inject: "true"
    consul.hashicorp.com/connect-service-protocol: "tcp"
    consul.hashicorp.com/connect-service-port: "8200"
    consul.hashicorp.com/service-tags: "secondary"

  service:
    enabled: true
    type: LoadBalancer
    port: 8200
    targetPort: 8200
    annotations:
      external-dns.alpha.kubernetes.io/hostname: "vault-2-server.ric.gcp.hashidemos.io"
      consul.hashicorp.com/service-sync: 'true'

  # extraEnvironmentVars is a list of extra enviroment variables to set with the stateful set. These could be
  # used to include variables required for auto-unseal.
  extraEnvironmentVars:
    VAULT_CACERT: /vault/userconfig/vault-server-tls/vault.ca


  # extraVolumes is a list of extra volumes to mount. These will be exposed
  # to Vault in the path `/vault/userconfig/<name>/`.
  extraVolumes:
    - type: secret
      name: vault-server-tls
    - type: secret
      name: tls-ca-cluster-1
    - type: secret
      name: vault-kms-config

  extraArgs: "-config=/vault/userconfig/vault-kms-config/seal_config.hcl"

  # Run Vault in "HA" mode.
  ha:
    enabled: true
    replicas: 3
    apiAddr: "https://vault-2.ric.gcp.hashidemos.io:8200"
    raft:
      enabled: true

      config: |
        ui = true
        log_level = "Debug"
        listener "tcp" {
          address = "[::]:8200"
          tls_cert_file = "/vault/userconfig/vault-server-tls/vault.crt"
          tls_key_file = "/vault/userconfig/vault-server-tls/vault.key"
          tls_client_ca_file = "/vault/userconfig/vault-server-tls/vault.ca"
          tls_disable_client_certs = true
        }

        cluster_addr = "https://vault-2.ric.gcp.hashidemos.io:8201"

        storage "raft" {
          path = "/vault/data"
          retry_join {
            leader_api_addr = "https://vault-0.vault-internal:8200"
            leader_ca_cert_file = "/vault/userconfig/vault-server-tls/vault.ca"
          }
          retry_join {
            leader_api_addr = "https://vault-1.vault-internal:8200"
            leader_ca_cert_file = "/vault/userconfig/vault-server-tls/vault.ca"
          }
          retry_join {
            leader_api_addr = "https://vault-2.vault-internal:8200"
            leader_ca_cert_file = "/vault/userconfig/vault-server-tls/vault.ca"
          }
        }

        service_registration "kubernetes" {}

        replication {
          resolver_discover_servers = false
        }

# Vault UI
ui:
  enabled: true
  serviceType: "LoadBalancer"
  externalPort: 8200
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "vault-2.ric.gcp.hashidemos.io"
  # For Added Security, edit the below
  #loadBalancerSourceRanges:
  #   - < Your IP RANGE Ex. 10.0.0.0/16 >
  #   - < YOUR SINGLE IP Ex. 1.78.23.3/32 >
