---
apiVersion: v1
kind: Service
metadata:
  annotations:
    consul.hashicorp.com/service-sync: "true"
    external-dns.alpha.kubernetes.io/hostname: boundary-api.ric.gcp.hashidemos.io
  name: boundary-api
  labels:
    app: boundary
  namespace: boundary
spec:
  type: LoadBalancer
  ports:
   - port: 9200
     protocol: TCP
  selector:
    app: boundary

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    consul.hashicorp.com/service-sync: "true"
    external-dns.alpha.kubernetes.io/hostname: boundary-cluster.ric.gcp.hashidemos.io
  name: boundary-cluster
  labels:
    app: boundary
  namespace: boundary
spec:
  type: LoadBalancer
  ports:
   - port: 9201
     protocol: TCP
  selector:
    app: boundary

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    consul.hashicorp.com/service-sync: "true"
    external-dns.alpha.kubernetes.io/hostname: boundary-proxy.ric.gcp.hashidemos.io
  name: boundary-proxy
  labels:
    app: boundary
  namespace: boundary
spec:
  type: LoadBalancer
  ports:
   - port: 9202
     protocol: TCP
  selector:
    app: boundary
