---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-1
  namespace: webapp
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9102"
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/connect-service-protocol: "http"
        consul.hashicorp.com/connect-service-port: "5000"
        consul.hashicorp.com/connect-service-upstreams: "external-counting.default:9001:cluster-1"
        consul.hashicorp.com/service-tags: "v3"
        consul.hashicorp.com/service-meta-version: "v3"
      labels:
        app: webapp
    spec:
      serviceAccountName: webapp
      containers:
      - name: webapp
        image: ghcr.io/gitrgoliveira/minikube-consul/webapp:v2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
          name: http
        env:
        - name: COUNTING_SERVICE_URL
          value: "http://localhost:9001"
        - name: BG_COLOR
          value: "KHAKI"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-2
  namespace: webapp
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9102"
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/connect-service-protocol: "http"
        consul.hashicorp.com/connect-service-port: "5000"
        consul.hashicorp.com/connect-service-upstreams: "external-counting.default:9001:cluster-1"
        consul.hashicorp.com/service-tags: "v3"
        consul.hashicorp.com/service-meta-version: "v3"
      labels:
        app: webapp
    spec:
      serviceAccountName: webapp
      containers:
      - name: webapp
        image: ghcr.io/gitrgoliveira/minikube-consul/webapp:v2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
          name: http
        env:
        - name: COUNTING_SERVICE_URL
          value: "http://localhost:9001"
        - name: BG_COLOR
          value: "PAPAYAWHIP"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-3
  namespace: webapp
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9102"
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/connect-service-protocol: "http"
        consul.hashicorp.com/connect-service-port: "5000"
        consul.hashicorp.com/connect-service-upstreams: "external-counting.default:9001:cluster-1"
        consul.hashicorp.com/service-tags: "v3"
        consul.hashicorp.com/service-meta-version: "v3"
      labels:
        app: webapp
    spec:
      serviceAccountName: webapp
      containers:
      - name: webapp
        image: ghcr.io/gitrgoliveira/minikube-consul/webapp:v2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
          name: http
        env:
        - name: COUNTING_SERVICE_URL
          value: "http://localhost:9001"
        - name: BG_COLOR
          value: "PAPAYAWHIP"

